@echo off
title DevKit No Git
set "ROOT=%~dp0"
call "%ROOT%paths.bat"
call "%SYNPATH_OTHERS%\joinfiles.bat"
cls
set "PATH=%SYNPATH_CADDY%;%PATH%"
set "PATH=%SYNPATH_CONSUL%;%PATH%"
set "PATH=%SYNPATH_CURL%\bin;%PATH%"
set "PATH=%SYNPATH_ETCD%;%PATH%"
set "PATH=%SYNPATH_NPP%;%PATH%"
attrib +r "%SYNPATH_NPP%\config.xml"
set "PATH=%SYNPATH_HEIDISQL%;%PATH%"
set "PATH=%SYNPATH_SQLITESTUDIO%;%PATH%"
set "PATH=%SYNPATH_WINMERGE%;%PATH%"
set "PATH=%SYNPATH_GEANY%\bin;%PATH%"
set "PATH=%SYNPATH_ZED%;%PATH%"
set "PATH=%SYNPATH_VSCODE%;%PATH%"
set "PATH=%SYNPATH_CODEBLOCKS%;%PATH%"
set "PATH=%SYNPATH_NODE%;%PATH%"
set "PATH=%SYNPATH_PYTHON%;%PATH%"
set "PATH=%SYNPATH_PYTHON%\Scripts;%PATH%"
set "PATH=%SYNPATH_PHP%;%PATH%"
set "PATH=%SYNPATH_JDK%\bin;%PATH%"
set "PATH=%SYNPATH_COMPOSER%;%PATH%"
set "PATH=%SYNPATH_OTHERS%;%PATH%"
set "PATH=%SYNPATH_GO%\bin;%PATH%"
set "GOPATH=%SYNPATH_GO%\gopath"
set "GOCACHE=%SYNPATH_GO%\gocache"
set "GOTELEMETRYDIR=%SYNPATH_GO%\gotelemetry"
set "npm_config_prefix=%SYNPATH_NODE%\node_global"
set "PATH=%SYNPATH_RUST%\rustc\bin;%PATH%"
set "PATH=%SYNPATH_RUST%\cargo\bin;%PATH%"
set "RUSTFLAGS=--sysroot=%SYNPATH_RUST%\rust-std-x86_64-pc-windows-gnu"
set "CARGO_HOME=%SYNPATH_RUST%\cargo"
set "PATH=%npm_config_prefix%;%PATH%"
set "PATH=%SYNPATH_NIM%\bin;%PATH%"
set "PATH=%SYNPATH_ZIG%;%PATH%"
set "PATH=%SYNPATH_CPP%\bin;%PATH%"
set "PATH=%SYNPATH_MARIADB%;%PATH%"
set "PATH=%SYNPATH_MARIADB%\bin;%PATH%"
set "PATH=%SYNPATH_POSGRESQL%;%PATH%"
set "PATH=%SYNPATH_POSGRESQL%\bin;%PATH%"
set "PATH=%SYNPATH_POSGRESQL%\pgAdmin 4\runtime;%PATH%"
cmd.exe /k "echo [Minh Nguyen DevKit NoGit Shell Ready] && echo code, sqlitestudio, winmergeu, notepad++, heidisql, geany, codeblocks, git gui, start-mariadb, stop-mariadb, start-postgresql, stop-postgresql && cd /d %ROOT%"
